//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Address
    {
        public int AddressId { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Pincode { get; set; }
        public int UserId { get; set; }
    
        public virtual T_Users T_Users { get; set; }
    }
}
