//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Car
    {
        public T_Car()
        {
            this.T_Rent = new HashSet<T_Rent>();
            this.T_Reservation = new HashSet<T_Reservation>();
        }
    
        public int CarId { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public int Stock { get; set; }
        public string Model { get; set; }
        public int SeatQuantity { get; set; }
        public string FuelType { get; set; }
        public int Mileage { get; set; }
        public double DailyPrice { get; set; }
    
        public virtual ICollection<T_Rent> T_Rent { get; set; }
        public virtual ICollection<T_Reservation> T_Reservation { get; set; }
    }
}
