//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Reservation
    {
        public T_Reservation()
        {
            this.T_Rent = new HashSet<T_Rent>();
        }
    
        public int ResId { get; set; }
        public System.DateTime ResDate { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int CarId { get; set; }
        public int UserId { get; set; }
    
        public virtual T_Car T_Car { get; set; }
        public virtual ICollection<T_Rent> T_Rent { get; set; }
        public virtual T_Users T_Users { get; set; }
    }
}
