//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Rent
    {
        public int RentId { get; set; }
        public int TotalRentDay { get; set; }
        public double DailyRentFee { get; set; }
        public double FuelCharge { get; set; }
        public double Total { get; set; }
        public double Refund { get; set; }
        public int CarId { get; set; }
        public int UserId { get; set; }
        public int ResId { get; set; }
    
        public virtual T_Car T_Car { get; set; }
        public virtual T_Users T_Users { get; set; }
        public virtual T_Reservation T_Reservation { get; set; }
    }
}
