//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        public T_Users()
        {
            this.T_OTP_Details = new HashSet<T_OTP_Details>();
            this.T_PasswordHistoryLog = new HashSet<T_PasswordHistoryLog>();
            this.T_Address = new HashSet<T_Address>();
            this.T_Customers = new HashSet<T_Customers>();
            this.T_Rent = new HashSet<T_Rent>();
            this.T_Reservation = new HashSet<T_Reservation>();
        }
    
        public int UserId_ { get; set; }
        public string EmailId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public bool IsOnline { get; set; }
        public bool IsLocked { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<T_OTP_Details> T_OTP_Details { get; set; }
        public virtual ICollection<T_PasswordHistoryLog> T_PasswordHistoryLog { get; set; }
        public virtual T_Roles T_Roles { get; set; }
        public virtual ICollection<T_Address> T_Address { get; set; }
        public virtual ICollection<T_Customers> T_Customers { get; set; }
        public virtual ICollection<T_Rent> T_Rent { get; set; }
        public virtual ICollection<T_Reservation> T_Reservation { get; set; }
    }
}
